# TCS Data Challenge


# Clustering

1 - Data Loading

In [0]:
# Required imports

from google.colab import auth
auth.authenticate_user()
import gspread
from oauth2client.client import GoogleCredentials
gc = gspread.authorize(GoogleCredentials.get_application_default()) # for loading directly from the link

import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn import metrics
from sklearn.cluster import AgglomerativeClustering
from sklearn.preprocessing import OneHotEncoder

In [3]:
# Get the dataset

wb = gc.open_by_url('https://docs.google.com/spreadsheets/d/1gUvcoy9I1c0vuuNgKeFVQ1OnpRimJ2M7LpVtUROa8w8/edit?usp=sharing')
sheet = wb.worksheet('TCS_data89')
raw_data = sheet.get_all_values()
data_main = pd.DataFrame.from_records(raw_data[1:], columns=raw_data[0])
data_main.head()

           Timestamp  ...  Option#2 ) Audio / Video format- Record your perspective in audio or video.- Save it as MPG, MPEG, AVI, etc
0  6/6/2020 14:42:19  ...
1  6/6/2020 15:15:46  ...
2  6/6/2020 15:51:37  ...
3  6/6/2020 15:58:54  ...
4  6/6/2020 20:57:33  ...

[5 rows x 41 columns]

In [4]:
column_names = ['timestamp', 'consumerism', 'hear_survey', 'country_in', 'citystate_in', 'age_group', 'gender', 'race_enthnicity', #8
                'family_size', 'household_income_pa', 'education', 'profession', 'residence', 'pandemic_interpretation', 'new_normal', #15
                'expen_impt_food_groceries', 'expen_impt_healthcare', 'expen_impt_utilities', 'expen_impt_residence', 
                'expen_impt_education', 'expen_impt_entertainment', 'expen_impt_appliances', 'expen_impt_highvalue', 
                'expen_impt_business_expen', 'expen_impt_wellness', 'expen_impt_luxury', 'expen_impt_insurance', 
                'expen_impt_investments', 'expen_impt_other', #29
                'postcov_life_simplifier', 'postcov_degrowth_activist', 'postcov_climate_activist', 'postcov_sane_food', 
                'postcov_conservationist', 'postcov_remote_everything', 'postcov_most', 'postcov_little', 'postcov_no_change', 'postcov_other', #39
                'perspective_text', 'perspective_other'] #41
data_main.columns = column_names
data_main.head()

           timestamp  ... perspective_other
0  6/6/2020 14:42:19  ...
1  6/6/2020 15:15:46  ...
2  6/6/2020 15:51:37  ...
3  6/6/2020 15:58:54  ...
4  6/6/2020 20:57:33  ...

[5 rows x 41 columns]

2 - Missing data analysis and imputation

In [5]:
data_main = data_main.replace('', np.nan)
data_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 41 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   timestamp                  89 non-null     object
 1   consumerism                87 non-null     object
 2   hear_survey                84 non-null     object
 3   country_in                 85 non-null     object
 4   citystate_in               87 non-null     object
 5   age_group                  86 non-null     object
 6   gender                     87 non-null     object
 7   race_enthnicity            87 non-null     object
 8   family_size                86 non-null     object
 9   household_income_pa        82 non-null     object
 10  education                  87 non-null     object
 11  profession                 87 non-null     object
 12  residence                  86 non-null     object
 13  pandemic_interpretation    86 non-null     object
 14  new_normal                 87 non-null     object
 15  expen_impt_food_groceries  74 non-null     object
 16  expen_impt_healthcare      70 non-null     object
 17  expen_impt_utilities       69 non-null     object
 18  expen_impt_residence       66 non-null     object
 19  expen_impt_education       67 non-null     object
 20  expen_impt_entertainment   76 non-null     object
 21  expen_impt_appliances      71 non-null     object
 22  expen_impt_highvalue       75 non-null     object
 23  expen_impt_business_expen  70 non-null     object
 24  expen_impt_wellness        71 non-null     object
 25  expen_impt_luxury          74 non-null     object
 26  expen_impt_insurance       68 non-null     object
 27  expen_impt_investments     70 non-null     object
 28  expen_impt_other           31 non-null     object
 29  postcov_life_simplifier    83 non-null     object
 30  postcov_degrowth_activist  80 non-null     object
 31  postcov_climate_activist   81 non-null     object
 32  postcov_sane_food          80 non-null     object
 33  postcov_conservationist    79 non-null     object
 34  postcov_remote_everything  79 non-null     object
 35  postcov_most               76 non-null     object
 36  postcov_little             73 non-null     object
 37  postcov_no_change          77 non-null     object
 38  postcov_other              27 non-null     object
 39  perspective_text           29 non-null     object
 40  perspective_other          0 non-null      float64
dtypes: float64(1), object(40)
memory usage: 28.6+ KB

In [18]:
data_main = data_main[data_main['consumerism'].notna()]
data_to_cluster = data_main[['country_in', 'age_group', 'gender', 'race_enthnicity', 'family_size', 'household_income_pa', 
                             'education', 'profession', 'residence', 'pandemic_interpretation']]
# data_to_cluster.head()
data_to_cluster.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 87 entries, 1 to 88
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   country_in               85 non-null     object
 1   age_group                86 non-null     object
 2   gender                   87 non-null     object
 3   race_enthnicity          87 non-null     object
 4   family_size              86 non-null     object
 5   household_income_pa      82 non-null     object
 6   education                87 non-null     object
 7   profession               87 non-null     object
 8   residence                86 non-null     object
 9   pandemic_interpretation  86 non-null     object
dtypes: object(10)
memory usage: 7.5+ KB

In [19]:
def get_string_list(x):
    if type(x['pandemic_interpretation']) == str:
        # return x['pandemic_interpretation'].split(', ')
        split = x['pandemic_interpretation'].split(', ')
        if 'Family' in split:
            split.remove('Family')
            split.remove('friends and community come first')
            split.append('Family, friends and community come first')

        if 'More home cooking' in split:
            split.remove('More home cooking')
            split.remove('more kitchen gardening and less eating out')
            split.append('More home cooking more kitchen gardening and less eating out')

        if 'Have become more conscious of fragility of the planet' in split:
            split.remove('Have become more conscious of fragility of the planet')
            split.remove('of air and water pollution')
            split.append('Have become more conscious of fragility of the planet of air and water pollution')

        return split
    else:
        return []

data_to_cluster2 = data_to_cluster.copy()
string_list = data_to_cluster.apply(get_string_list, axis=1)
data_to_cluster2['pandemic_interpretation'] = string_list
# data_to_cluster2.head()


from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
data_to_cluster2 = data_to_cluster2.join(pd.DataFrame(mlb.fit_transform(data_to_cluster2.pop('pandemic_interpretation')),
                                                    columns=mlb.classes_,
                                                    index=data_to_cluster.index))
data_to_cluster2.head()

      country_in  ... Will spend and save money more carefully
1          India  ...                                        0
2          India  ...                                        1
3          India  ...                                        0
4  United States  ...                                        0
5          India  ...                                        0

[5 rows x 18 columns]

https://towardsdatascience.com/clustering-with-k-means-1e07a8bfb7ca

In [21]:
ohe_data_to_cluster = pd.get_dummies(data_to_cluster2[['country_in', 'age_group', 'gender', 'race_enthnicity', 'family_size', 'household_income_pa', 
                               'education', 'profession', 'residence']])
data_to_cluster2 = pd.concat([data_to_cluster2.drop(['country_in', 'age_group', 'gender', 'race_enthnicity', 'family_size', 'household_income_pa', 
                                  'education', 'profession', 'residence'], axis=1), 
           ohe_data_to_cluster], axis=1)
data_to_cluster2.head()

   Family, friends and community come first  ...  residence_town-home
1                                         0  ...                    1
2                                         1  ...                    0
3                                         1  ...                    0
4                                         1  ...                    0
5                                         0  ...                    0

[5 rows x 73 columns]

In [22]:
data_to_cluster2.shape

(87, 73)

In [25]:
#Set number of clusters at initialisation time
# 2 clusters
k_means = KMeans(n_clusters=3)
#Run the clustering algorithm
model = k_means.fit(data_to_cluster2)
model
#Generate cluster predictions and store in y_hat
y_hat = k_means.predict(data_to_cluster2)
y_hat

array([1, 1, 0, 2, 1, 0, 2, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 2, 1, 0, 1, 1,
       1, 0, 1, 2, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 2, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       2, 1, 2, 1, 1, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 1, 0],
      dtype=int32)